// This file is generated by Prismic local builder. Update with care!

export { default as Banner } from './Banner'
export { default as Product } from './Product'
export { default as TopProducts } from './TopProducts'
